name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t gcr.io/$GCP_PROJECT_ID/devops-app:latest ./docker

      - name: Push to Google Container Registry
        run: |
          echo $GCP_SA_KEY > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker
          docker push gcr.io/$GCP_PROJECT_ID/devops-app:latest
